### PR TITLE
Remove std::exit

### LINKED ISSUE #36: Remove std::exit calls
Replace calls to `std::exit` with `throw base_error` to allow for better and more precise error-handling.

### PR DESCRIPTION
**Pull request by Ragusaen**
#36

### CODE REVIEW

**Review by petergjoel — CHANGES_REQUESTED** [review]
Looks good, two changes:
(1) remove "Fatal error:" and "Error:" (and similar)
(2) add a try/catch around the body of main and make a pretty-print like 
`std::cerr << "ERROR: " << e.what() << std::endl; std::exit(-1);`
on failure.

**Review by petergjoel — APPROVED** [review]
LGTM.

**Review by srba — CHANGES_REQUESTED** [review]
Please, prefix all the messages with "Error: xxx" so that we can search the output and search for this keywords - so every abnormal termination should be prefixed with "Error".

**Review by srba — APPROVED** [review]
okay

**Pull request merged**
