### PR TITLE
Changed pushnegation and simplify to visitor pattern

### PR DESCRIPTION
**Pull request by Ragusaen**

### CODE REVIEW

**Comment by petergjoel** [comment]
@srba this should be ready for merging (assuming that the build passes)

**Comment by srba** [comment]
@petergjoel, has it been checked for consistency?

**Comment by petergjoel** [comment]
This branch has quite a bit of regressions (I tested only on colored nets).
1. there seems to be some debug-print gone wild, I get megabyte-sized files with outputs like 
```
((not is-fireable(beginExtAcc)) and (not is-fireable(reqExtAcc)) and (not is-fireable(endOwnAcc)))
((is-fireable(beginExtAcc) or (not is-fireable(reqExtAcc))) and (not is-fireable(endOwnAcc)) and (not is-fireable(endOwnAcc)) and is-fireable(beginOwnAcc))
```
2. there is a drop in performance across all query types:
```
MCC21-6-COL.trunk-252.ReachabilityCardinality -> 3206
MCC21-6-COL.a06594b7.ReachabilityCardinality -> 3102
MCC21-6-COL.trunk-252.ReachabilityFireability -> 2788
MCC21-6-COL.a06594b7.ReachabilityFireability -> 1469
```
3. there is a few failed models:
```
BART-COL-002-ReachabilityFireability-01
BART-COL-002-ReachabilityFireability-03
BART-COL-002-ReachabilityFireability-10
BART-COL-030-ReachabilityFireability-00
BART-COL-040-ReachabilityFireability-01
BART-COL-040-ReachabilityFireability-08
BART-COL-040-ReachabilityFireability-12
BART-COL-040-ReachabilityFireability-14
BART-COL-060-ReachabilityFireability-00
BART-COL-060-ReachabilityFireability-02
BART-COL-060-ReachabilityFireability-04
BART-COL-060-ReachabilityFireability-15
```

**Comment by petergjoel** [comment]
With last few commits, this now has comparable performance to main.

**Review by srba — APPROVED** [review]

**Pull request merged**
